spring:
  application:
    name: house
  config:
    activate:
      on-profile: stage
  datasource:
    url: jdbc:postgresql://db:5432/house_db
    username: postgres
    password: root
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 10MB
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        default_schema: public
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: applicationhouse4@gmail.com
    password: boyj manf avaw tslv
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
  mvc:
    static-path-pattern: /swagger*
server:
  port: 8080
base:
  web:
    url: http://localhost:4200
  url: http://localhost:8080
mail:
  from: hello@demomailtrap.com
jwt:
  expiration: 860000
secret:
  key: 0nZyJqOE91Af62zEjyq64unY8hex9eIc0nZyJqOE91Af62zEjyq64unY8hex9eIc
logging:
  file:
    name: ./logs/dev.log