spring:
  application:
    name: house
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/house_db
    username: postgres
    password: root
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 10MB
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        default_schema: public
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  mail:
    host: live.smtp.mailtrap.io
    port: 587
    username: api
    password: db2acb161d5f78c860e16da55901d57b
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
  mvc:
    static-path-pattern: /swagger*
server:
  port: 8090
base:
  url: http://localhost:9090
mail:
  from: hello@demomailtrap.com
jwt:
  expiration: 86000000
secret:
  key: 0nZyJqOE91Af62zEjyq64unY8hex9eIc0nZyJqOE91Af62zEjyq64unY8hex9eIc
logging:
  file:
    name: ./logs/dev.log