spring:
  application:
    name: house
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 10MB
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        default_schema: public
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: applicationhouse4@gmail.com
    password: boyj manf avaw tslv
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
  mvc:
    static-path-pattern: /swagger*
server:
  port: 8080
base:
  web:
    url: https://apartment-house-application.vercel.app
  url: https://house-application-2c2abb3720c7.herokuapp.com
mail:
  from: hello@demomailtrap.com
jwt:
  expiration: 860000
secret:
  key: 0nZyJqOE91Af62zEjyq64unY8hex9eIc0nZyJqOE91Af62zEjyq64unY8hex9eIc
logging:
  file:
    name: ./logs/dev.log